spring:
  banner:
    image:
      location: banner.jpg

casorio:
  apis:
    prefix: /rest
  queues:
    message:
      url: casorio-sqs-queue-message
  authentication:
    path: "/auth"

server:
  error:
    include-binding-errors: always
    include-message: always

security:
  jwt:
    expiration: 3600
    secret: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"