spring:
  banner:
    image:
      location: banner.jpg

casorio:
  apis:
    prefix: /rest
  queues:
    message:
      url: casorio-sqs-queue-message

management:
  endpoints:
    web:
      exposure:
        include: "*"