spring:
  banner:
    image:
      location: banner.jpg

casorio:
  apis:
    prefix: /rest
  queues:
    message:
      url: casorio-sqs-queue-message

server:
  error:
    include-binding-errors: always
    include-message: always


management:
  endpoints:
    web:
      exposure:
        include: "*"